name: LMS Automation CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run Chrome
        run: ./gradlew clean test -Dbrowser=chrome

      - name: Run Firefox
        run: ./gradlew clean test -Dbrowser=firefox