name: LMS Automation CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ======================
      # INSTALL BROWSERS
      # ======================
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Firefox
        run: |
          sudo apt-get install -y firefox

      # ======================
      # RUN TEST
      # ======================
      - name: Run Automation Test
        run: ./gradlew clean test -Dbrowser=${{ matrix.browser }}

      # ======================
      # UPLOAD REPORT
      # ======================
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.browser }}
          path: reports/