name: LMS Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🔥 INI YANG PENTING BANGET
      - name: Give permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test -Dbrowser=${{ matrix.browser }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.browser }}
          path: build/reports/